on:
  issue_comment:
    types: [created]
    
name: Deploy POI to Production

jobs:
  react-on-issue-comment-not-approved:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'Approve POI Deploy to Production') && startsWith(github.event.comment.body, '/approve')
    steps:
    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Swap the slot
      run: az webapp deployment slot swap -g openhackf1c9cxe9rg -n openhackf1c9cxe9poi --slot staging --target-slot production
    - name: Get versions in prod / staging
      run: |
        staging=`az webapp config container show -n openhackf1c9cxe9poi --slot staging -g openhackf1c9cxe9rg | grep openhackf1c9cxe9acr.azurecr.io/devopsoh/api-poi | awk '{print $2}'`
        prod=`az webapp config container show -n openhackf1c9cxe9poi -g openhackf1c9cxe9rg | grep openhackf1c9cxe9acr.azurecr.io/devopsoh/api-poi | awk '{print $2}'`
        echo ::set-env name=staging-version::${staging:8:-1}
        echo ::set-env name=prod-version::${prod:8:-1} 
    - name: Comment on Issue
      uses: actions/github-script@0.9.0
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Please verify deployment was successful before closing. In case of issues type `/approve` again to swap things back.<br><br>Current version in prod: ${{ env.prod-version }}<br><br>Version in staging: ${{ env.staging-version }}'
          })
